-- =============================================================================
-- 007: Seed UNESCO CFT Pilot Scenarios (20 scenarios)
-- Source: reasonlens-research/cft-pilot/frameworks/teacher-competency/scenarios.json
-- Licence: CC BY-SA 3.0 IGO — derivative work, share-alike applies
-- =============================================================================

-- ─── Scenario Bank (20 scenario stems) ───

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-HC-AD-01', 'teacher-competency', 'tc-human-centered', 'Human-Centered Mindset', 'acquire-deepen', 'Acquire', 'Deepen', 'Your head of department asks everyone to trial an AI-powered marking assistant that provides automated feedback on student essays. Before it goes live with students, what would you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-HC-AD-02', 'teacher-competency', 'tc-human-centered', 'Human-Centered Mindset', 'acquire-deepen', 'Acquire', 'Deepen', 'A free AI tutoring app is becoming popular with your students. Several are using it for homework support. You want to check whether it is suitable for all your students. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-HC-DC-01', 'teacher-competency', 'tc-human-centered', 'Human-Centered Mindset', 'deepen-create', 'Deepen', 'Create', 'Your institution is about to invest in an AI-powered student support platform. You have concerns about whether it genuinely keeps human needs at the centre. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-HC-DC-02', 'teacher-competency', 'tc-human-centered', 'Human-Centered Mindset', 'deepen-create', 'Deepen', 'Create', 'Several departments in your institution are adopting AI tools independently, with no shared approach to ensuring these tools keep human needs central. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-ETH-AD-01', 'teacher-competency', 'tc-ethics', 'Ethics of AI', 'acquire-deepen', 'Acquire', 'Deepen', 'A colleague shows you an AI tool that generates personalised reading lists for students based on their past performance data. They are enthusiastic and want to start using it next term. What would you do before it goes live with students?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-ETH-AD-02', 'teacher-competency', 'tc-ethics', 'Ethics of AI', 'acquire-deepen', 'Acquire', 'Deepen', 'You notice that an AI writing assistant your students use seems to give more detailed feedback on essays written in formal academic English than on essays written in a more colloquial or dialect-influenced style. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-ETH-DC-01', 'teacher-competency', 'tc-ethics', 'Ethics of AI', 'deepen-create', 'Deepen', 'Create', 'Your institution currently has no specific guidelines for how staff should evaluate AI tools for ethical concerns before using them with students. Individual teachers make their own decisions. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-ETH-DC-02', 'teacher-competency', 'tc-ethics', 'Ethics of AI', 'deepen-create', 'Deepen', 'Create', 'A teacher in another department asks you for advice on how to check an AI tool for potential bias. They know you have done this before. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-FO-AD-01', 'teacher-competency', 'tc-foundations', 'AI Foundations', 'acquire-deepen', 'Acquire', 'Deepen', 'A student asks you: ''My ChatGPT essay had fake references that looked completely real. Why does it do that?'' How do you respond?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-FO-AD-02', 'teacher-competency', 'tc-foundations', 'AI Foundations', 'acquire-deepen', 'Acquire', 'Deepen', 'A colleague says: ''I asked ChatGPT the same question twice and got completely different answers. Is it broken?'' What do you say?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-FO-DC-01', 'teacher-competency', 'tc-foundations', 'AI Foundations', 'deepen-create', 'Deepen', 'Create', 'Your department has decided that all students should understand the basics of how AI works before they use AI tools in their coursework. You are asked to help make this happen. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-FO-DC-02', 'teacher-competency', 'tc-foundations', 'AI Foundations', 'deepen-create', 'Deepen', 'Create', 'A group of colleagues say they want to understand AI better but find the available training too technical. They ask if you can help. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-PD-AD-01', 'teacher-competency', 'tc-pedagogy', 'AI Pedagogy', 'acquire-deepen', 'Acquire', 'Deepen', 'You want to improve how quickly students get feedback on their written work. You have access to an AI tool that can analyse student writing. How do you use it?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-PD-AD-02', 'teacher-competency', 'tc-pedagogy', 'AI Pedagogy', 'acquire-deepen', 'Acquire', 'Deepen', 'You teach a mixed-ability class. Some students finish tasks quickly while others need more time and support. You want to use AI to help personalise the learning experience. What approach do you take?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-PD-DC-01', 'teacher-competency', 'tc-pedagogy', 'AI Pedagogy', 'deepen-create', 'Deepen', 'Create', 'You have been successfully using AI for formative assessment in several of your lessons. Your programme leader asks you to think about how AI could be embedded more systematically across the whole module. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-PD-DC-02', 'teacher-competency', 'tc-pedagogy', 'AI Pedagogy', 'deepen-create', 'Deepen', 'Create', 'Your institution is redesigning a programme and wants to include AI as a feature. You are asked to contribute to the curriculum design. What is your approach?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-PL-AD-01', 'teacher-competency', 'tc-professional', 'Professional Learning', 'acquire-deepen', 'Acquire', 'Deepen', 'You have just attended a really useful workshop about using AI for assessment. A colleague who could not attend asks what it was like. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-PL-AD-02', 'teacher-competency', 'tc-professional', 'Professional Learning', 'acquire-deepen', 'Acquire', 'Deepen', 'You discover an AI tool that is genuinely useful for your teaching. Several colleagues teach similar subjects. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-PL-DC-01', 'teacher-competency', 'tc-professional', 'Professional Learning', 'deepen-create', 'Deepen', 'Create', 'Your institution wants to upskill all teaching staff in using AI tools. You are recognised as someone with good AI knowledge. You are asked to help. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

INSERT INTO scenario_bank (scenario_id, framework_id, dimension_id, dimension_name, target_boundary, target_lower_level, target_upper_level, stem, context_tags, status, source_attribution)
VALUES ('CFT-PL-DC-02', 'teacher-competency', 'tc-professional', 'Professional Learning', 'deepen-create', 'Deepen', 'Create', 'Several new teachers have joined your department and have little experience with AI in education. You want to support their development. What do you do?', '{"subject_area":"universal","institution_level":"universal","institution_type":"universal","region":"universal"}'::jsonb, 'draft', '{"source_framework":"UNESCO AI Competency Framework for Teachers","source_licence":"CC BY-SA 3.0 IGO","content_type":"derivative","attribution_text":"Based on the UNESCO AI Competency Framework for Teachers (2024). Scenarios created by ReasonLens.","share_alike_applies":true}'::jsonb);

-- ─── Response Options ───

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-AD-01', 'A', 'Try it out on a few of your own past assignments to see if the feedback it gives is sensible and matches your professional judgement.', 'Acquire', 1, true, 'Testing output quality feels responsible and proactive. But the evaluation only checks whether feedback is good, not whether it works equitably for all students. There is no check for accessibility, cultural bias, or whether it disadvantages certain groups.', NULL, 'No diversity testing, no accessibility check, no evaluation of language support, no documentation');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-AD-01', 'B', 'Discuss with colleagues whether automated feedback might undermine the teacher-student relationship and whether students will feel the feedback is less personal.', 'Acquire', 1, true, 'This discussion sounds deeply human-centered because it raises relational concerns. But discussion about concerns is awareness. There is no structured evaluation action taken.', NULL, 'No structured evaluation, no testing, no documentation, no adopt/reject decision based on evidence');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-AD-01', 'C', 'Test the tool with essay samples from students with different backgrounds: EAL learners, students with dyslexia, students from different cultural contexts. Check whether feedback quality varies across these groups. Review the data privacy terms. Write up what you found.', 'Deepen', 2, false, NULL, 'Systematic diversity testing, accessibility check, data review, documentation of findings', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-AD-02', 'A', 'Ask a few students what they think of it and whether they find it helpful.', 'Acquire', 1, true, 'Gathering student voice sounds like responsible, human-centered practice. But asking a few students for opinions is informal awareness gathering, not structured evaluation against inclusive design criteria.', NULL, 'No systematic testing across demographics, no accessibility review, no data policy check, no documentation');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-AD-02', 'B', 'Test it yourself to see whether the explanations are accurate and age-appropriate.', 'Acquire', 1, false, NULL, NULL, 'Personal quality check only. No diversity testing, no accessibility or equity evaluation');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-AD-02', 'C', 'Check whether the app is accessible for students with additional needs. Test it with inputs in different languages your students speak. Review the privacy policy to see what data it collects about children. Record your findings in a brief report for your line manager.', 'Deepen', 2, false, NULL, 'Accessibility check, language support testing, data privacy review, documented report', NULL);
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-AD-02', 'D', 'Do all of the above checks, then create a simple evaluation template other teachers can reuse when students bring in new apps. Share it at the next staff meeting.', 'Create', 3, false, NULL, 'All Deepen behaviours plus institutional process creation and dissemination', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-DC-01', 'A', 'Evaluate the platform yourself using inclusive design criteria, document your concerns, and share them with your line manager in an email.', 'Deepen', 2, true, 'A thorough personal evaluation shared with management sounds like leadership. But this is individual Deepen practice: structured evaluation with communication. It does not involve organising institutional dialogue or shaping institutional decision-making processes.', NULL, 'No initiation of institutional conversation, no facilitation of cross-stakeholder discussion, no drafting of institutional guidance');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-DC-01', 'B', 'Discuss your concerns with trusted colleagues over coffee and encourage them to raise the issue in their own team meetings.', 'Deepen', 2, true, 'Mobilising colleagues feels like institutional leadership. But delegating the conversation to others'' team meetings is peer influence, not leading an institutional conversation.', NULL, 'No direct institutional engagement, no structured forum, no facilitated dialogue');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-DC-01', 'C', 'Request a slot on the relevant committee or decision-making group''s agenda. Prepare a structured briefing on human-centered design criteria for the platform. Facilitate a discussion with stakeholders including student representatives, IT, and teaching staff. Propose that the institution adopt specific human-centered evaluation criteria for all future AI procurements.', 'Create', 3, false, NULL, 'Proactive institutional engagement, structured facilitation, stakeholder inclusion, institutional process proposal', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-DC-02', 'A', 'Make sure your own department has a thorough process for evaluating AI tools against human-centered criteria and set a good example.', 'Deepen', 2, true, 'Leading by example within your own department feels like institutional influence. But department-level good practice without cross-institutional action is still individual/local Deepen.', NULL, 'No cross-departmental engagement, no institutional-level coordination, no broader guidance development');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-DC-02', 'B', 'Write a proposal for an institution-wide human-centered AI evaluation framework. Consult with department leads, IT, student representatives, and senior management. Present the framework at a governance meeting and advocate for its adoption as institutional policy.', 'Create', 3, false, NULL, 'Cross-institutional initiative, multi-stakeholder consultation, governance engagement, policy advocacy', NULL);
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-HC-DC-02', 'C', 'Raise it informally with other department heads when you see them and suggest someone should coordinate this.', 'Deepen', 2, false, NULL, NULL, 'No proactive leadership, no structured initiative, suggesting someone else should act');

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-AD-01', 'A', 'Try it out yourself to see if the recommendations are sensible and relevant to your subject area.', 'Acquire', 1, true, 'Feels responsible because the teacher is actively testing the tool. But the evaluation only checks output quality, not data practices, bias, or compliance. Surface-level evaluation is Acquire.', NULL, 'No investigation of data collection, no bias testing, no reference to institutional policy, no documentation');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-AD-01', 'B', 'Discuss with your colleague the ethical implications, including whether students should be told their data is being used and whether the tool might advantage some students over others.', 'Acquire', 1, true, 'Discussion of ethics sounds like Deepen-level engagement. But discussion without structured evaluation is awareness activity. The output is opinions and questions, not findings.', NULL, 'No structured evaluation process, no documentation, no decision framework');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-AD-01', 'C', 'Check what student data the tool collects and how it is stored. Test whether it gives different quality recommendations for students with different backgrounds. Review whether it aligns with your institution''s data protection policy. Write up your findings before making a decision.', 'Deepen', 2, false, NULL, 'Systematic data check, bias testing, policy alignment, documentation, explicit decision point', NULL);
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-AD-01', 'D', 'Do everything described in the previous option, and also draft a brief evaluation template that your department could reuse for any new AI tool. Share it with your head of department for adoption.', 'Create', 3, false, NULL, 'All Deepen behaviours plus institutional process creation, scaling beyond individual, seeking adoption', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-AD-02', 'A', 'Make a mental note that this is a potential bias issue and mention it to students so they are aware.', 'Acquire', 1, false, NULL, NULL, 'No structured investigation, no documentation, no systematic testing');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-AD-02', 'B', 'Discuss it with colleagues in the English department and agree that AI feedback tools are not perfect.', 'Acquire', 1, true, 'Collaborative discussion about a specific bias sounds like ethical practice. But the output is shared awareness, not structured evaluation. No checks are conducted and no documented findings are produced.', NULL, 'No systematic testing, no documentation, no recorded decision');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-AD-02', 'C', 'Run a structured test: submit several essay samples written in different styles and language registers. Compare the feedback quality across samples. Document the differences. Decide whether to continue using the tool, restrict its use, or raise the issue with the provider.', 'Deepen', 2, false, NULL, 'Systematic bias testing with controlled samples, documentation, decision-making based on findings', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-DC-01', 'A', 'Continue conducting your own thorough ethical evaluations of AI tools and encourage colleagues to do the same when the topic comes up.', 'Deepen', 2, true, 'Excellent personal practice plus informal encouragement feels like leadership. But without institutional action, it remains individual practice that depends on individual motivation and does not scale.', NULL, 'No institutional guideline development, no formal proposal, no stakeholder engagement');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-DC-01', 'B', 'Write a blog post or internal newsletter article about the importance of ethical AI evaluation and share your personal evaluation approach.', 'Deepen', 2, true, 'Publishing about ethics feels like thought leadership. But a blog post is personal publication, not institutional guideline development. It raises awareness but does not create institutional structures.', NULL, 'No institutional adoption process, no stakeholder consultation, no governance engagement');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-DC-01', 'C', 'Draft a set of ethical evaluation guidelines for AI tools. Consult with colleagues across different departments, data protection staff, and student representatives to refine them. Present the guidelines to the appropriate committee or leadership group and advocate for their adoption as institutional practice.', 'Create', 3, false, NULL, 'Guideline development, cross-stakeholder consultation, governance engagement, institutional adoption advocacy', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-DC-02', 'A', 'Walk them through the process you use: what to look for, how to test for bias, what questions to ask. Share your evaluation template with them.', 'Deepen', 2, true, 'Mentoring a colleague through the process feels like professional development facilitation. But reactive, one-to-one support is still Deepen-level sharing. It is not developing institutional guidelines.', NULL, 'No guideline development, no institutional-level action, no formal process creation');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-DC-02', 'B', 'Help them with their specific tool and then use the interaction as evidence that a shared, institutional approach is needed. Draft a brief proposal for an institution-wide AI ethics evaluation process. Include the evaluation criteria, a simple template, and a recommendation for who should be responsible. Present it to management.', 'Create', 3, false, NULL, 'Individual support plus institutional initiative, formal proposal development, process design, governance engagement', NULL);
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-ETH-DC-02', 'C', 'Point them to some good articles and resources about AI bias and suggest they start there.', 'Acquire', 1, false, NULL, NULL, 'No personal engagement, no structured guidance, passive resource referral');

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-AD-01', 'A', 'Explain that ChatGPT is AI, not a search engine, so it does not look things up. It sometimes makes mistakes, which is why you always need to check its work.', 'Acquire', 1, true, 'This answer is factually not wrong and gives practical advice. But it frames hallucination as ''making mistakes'', which does not explain the mechanism. The teacher knows AI is different from a search engine but does not explain why fabrication happens.', NULL, 'No explanation of the prediction mechanism, no connection between how LLMs generate text and why fabrication is a structural feature');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-AD-01', 'B', 'Tell the student that AI is not perfect and they should always verify references. This is a good lesson in critical thinking.', 'Below Acquire', 2, false, NULL, NULL, 'No understanding of AI vs non-AI distinction, no explanation of why this happens, generic advice');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-AD-01', 'C', 'Explain that ChatGPT generates text by predicting what word comes next based on patterns in its training data. It was trained on millions of academic texts that include references in a specific format. So when it writes an essay, it predicts that references should follow and generates text that looks like a reference because of the pattern, without checking whether the reference exists. It is completing a pattern, not retrieving facts.', 'Deepen', 2, false, NULL, 'Accurate explanation of the prediction mechanism, specific connection between mechanism and observed behaviour, clear distinction between pattern completion and fact retrieval', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-AD-02', 'A', 'Explain that AI tools are not always reliable and you need to use them carefully. Suggest they try asking the question more clearly.', 'Acquire', 1, true, 'Practical advice about careful use and clear prompting sounds informed. But the explanation does not address why variability occurs. The teacher knows AI is unreliable but cannot explain the mechanism.', NULL, 'No explanation of probabilistic generation, no understanding of why variability is a structural feature rather than a defect');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-AD-02', 'B', 'Reassure them it is normal. AI learns and updates, so answers change over time.', 'Below Acquire', 2, false, NULL, NULL, 'Incorrect explanation: response variability is not caused by learning or updating between queries. Demonstrates a fundamental misconception.');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-AD-02', 'C', 'Explain that ChatGPT does not store the correct answer and retrieve it. Each time you ask, it generates a fresh response by predicting the most probable next word. There is randomness built into this process so it does not always follow the same path. Getting different answers is not a bug; it is how the technology works. This is also why you should not treat any single output as the definitive answer.', 'Deepen', 2, false, NULL, 'Accurate explanation of generative mechanism, explanation of temperature/sampling, connection between mechanism and practical implication', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-DC-01', 'A', 'Prepare a clear explanation of how AI works and present it to students at the start of term. Include key points about limitations and when not to trust AI outputs.', 'Deepen', 2, true, 'Delivering a clear explanation to students sounds like teaching about AI. But a lecture or presentation is information delivery, not a designed learning activity. There are no learning objectives, no student activities, and no assessment of understanding.', NULL, 'No designed learning activities, no learning objectives, no hands-on elements, no assessment of student understanding');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-DC-01', 'B', 'Find some good videos and articles about how AI works and add them to the VLE for students to watch before the course starts.', 'Acquire', 1, false, NULL, NULL, 'No original design, no teaching activity, passive resource provision');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-DC-01', 'C', 'Design a workshop where students interact with an AI tool and observe its behaviour: give it the same prompt multiple times, test it with factual questions and compare to verified sources, ask it to explain its reasoning. Build in discussion activities where students articulate what they have learned about how AI generates responses. Assess understanding through a short reflection task. Iterate the workshop based on what works.', 'Create', 3, false, NULL, 'Designed learning activities with objectives, hands-on interaction, discussion, assessment, iteration', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-DC-02', 'A', 'Sit down with them over lunch and explain how LLMs work in plain language, answering their questions as they come up.', 'Deepen', 2, true, 'Explaining AI to colleagues in accessible language sounds like teaching about AI principles. But an informal conversation is reactive knowledge sharing, not designed learning. There are no objectives, no structured activities, and no way to check whether understanding was achieved.', NULL, 'No designed learning structure, no objectives, no activities for participants, no assessment of learning');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-DC-02', 'B', 'Design a short series of hands-on sessions specifically for non-technical colleagues. Each session focuses on one concept, includes activities where participants interact with AI tools and observe their behaviour, and ends with a check for understanding. Revise the sessions based on participant feedback.', 'Create', 3, false, NULL, 'Designed programme, audience-appropriate activities, hands-on learning, assessment, iteration', NULL);
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-FO-DC-02', 'C', 'Send them links to some beginner-friendly YouTube videos and online courses about AI.', 'Acquire', 1, false, NULL, NULL, 'No personal engagement, no design, passive resource referral');

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-AD-01', 'A', 'Use the AI tool to generate model answers and marking rubrics before the assessment. Share these with students in advance so they know what is expected.', 'Acquire', 1, true, 'Generating model answers and rubrics is assessment-related and feels like AI integration into assessment. But the AI''s role ends before students submit work. This is preparation, not formative assessment integration. The AI does not interact with actual student work.', NULL, 'AI is not part of the feedback loop. No AI analysis of student work, no personalised feedback, no adaptation based on student responses.');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-AD-01', 'B', 'Use the AI tool to generate the assignment brief and instructions, saving time on the preparation stage.', 'Acquire', 1, false, NULL, NULL, 'Clearly preparation only. No AI involvement in the assessment or feedback process.');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-AD-01', 'C', 'Set up a process where students submit drafts to the AI tool and receive initial feedback on structure, clarity, and common errors. You review the AI''s feedback to check accuracy. Students revise their work based on the combined AI and teacher feedback before final submission. You track which feedback points recur across the class to adjust your teaching.', 'Deepen', 2, false, NULL, 'AI in the feedback loop, teacher quality control, iterative revision cycle, diagnostic use of AI insights to inform teaching', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-AD-02', 'A', 'Use AI to generate three versions of each worksheet at different difficulty levels: foundation, standard, and extension. Give students the version that matches their current level.', 'Acquire', 1, true, 'Differentiated resources feel like personalised learning. But the AI''s role is only in preparation. The differentiation is teacher-directed and static. There is no adaptive element during the lesson and no AI involvement in the learning process itself.', NULL, 'AI used only for preparation. No AI-assisted adaptation during learning, no formative feedback loop, no real-time personalisation.');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-AD-02', 'B', 'Set up an AI-powered practice activity where the tool adjusts the difficulty of questions based on how each student performs. Students who answer correctly get harder questions; those who struggle get scaffolded support. You monitor the AI''s difficulty judgements and intervene where the AI is misjudging a student''s needs.', 'Deepen', 2, false, NULL, 'AI actively adapting during learning, real-time personalisation, teacher monitoring and quality control of AI decisions', NULL);
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-AD-02', 'C', 'Use AI to create a bank of practice questions at various difficulty levels. Print them out and let students self-select which level they attempt.', 'Acquire', 1, false, NULL, NULL, 'AI used for resource generation only. No AI involvement during the learning process.');

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-DC-01', 'A', 'Continue using AI in individual lessons where it works well and gradually add it to more lessons across the module as you find good applications.', 'Deepen', 2, true, 'Spreading AI use across the module feels like systematic curriculum integration. But adding AI to individual lessons incrementally is still lesson-level integration (Deepen). There is no coherent curriculum design where AI shapes the learning sequence.', NULL, 'No curriculum-level design, no learning sequence built around AI capabilities, no progressive skill development enabled by AI');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-DC-01', 'B', 'Redesign the module so that AI-assisted activities build on each other across the term. For example, early sessions use AI for low-stakes practice with feedback, mid-term sessions use AI for collaborative analysis tasks, and later sessions have students critically evaluating AI outputs as part of their assessed work. Document the rationale and evaluate impact on learning outcomes.', 'Create', 3, false, NULL, 'Coherent curriculum design, progressive AI integration across a learning sequence, pedagogically new approach, evaluation of impact', NULL);
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-DC-01', 'C', 'Write up your experience using AI in individual lessons as a case study and share it with the module team so they can adopt similar approaches.', 'Deepen', 2, false, NULL, NULL, 'Documentation and sharing of individual practice, not curriculum design');

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-DC-02', 'A', 'Suggest specific lessons where AI tools could be used for formative assessment or student practice, based on what has worked in your own teaching.', 'Deepen', 2, true, 'Contributing practical AI activity suggestions to a curriculum design process sounds like Create-level input. But suggesting individual activities is Deepen-level expertise applied to someone else''s curriculum, not designing an innovative curriculum yourself.', NULL, 'No curriculum-level design, no novel learning sequence, no pedagogical innovation enabled by AI');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-DC-02', 'B', 'Propose a curriculum structure where AI is not just used in individual activities but shapes the learning journey. Design learning outcomes that require AI interaction, progression from guided AI use to critical AI evaluation, and assessments that test students'' ability to work effectively with and without AI. Collaborate with the team to refine and validate the approach.', 'Create', 3, false, NULL, 'Curriculum-level design, AI-integrated learning outcomes, progressive design, collaborative development', NULL);
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PD-DC-02', 'C', 'Recommend specific AI tools the programme should adopt and provide training for staff on how to use them.', 'Deepen', 2, false, NULL, NULL, 'Tool recommendation is not curriculum design. Training support is professional learning, not pedagogy innovation.');

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-AD-01', 'A', 'Tell them it was good and suggest they sign up next time one is offered.', 'Acquire', 1, false, NULL, NULL, 'No knowledge sharing, no resource transfer, no added value for the colleague');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-AD-01', 'B', 'Give them a brief verbal summary of the key takeaways and forward the event email so they can see the slides.', 'Acquire', 1, true, 'Summarising and forwarding materials feels like sharing. But a verbal summary and a forwarded email are low-effort, low-context sharing. Deepen requires deliberate curation with explanation of relevance and application.', NULL, 'No contextualised recommendation, no explanation of how findings apply to the colleague''s specific practice, no curated resources');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-AD-01', 'C', 'Write up the three most useful things you learned, explain how each one applies to your department''s teaching context, and share the write-up with the whole team along with links to the resources you found most practical. Offer to show anyone who is interested how to get started.', 'Deepen', 2, false, NULL, 'Curated, contextualised sharing with explanation of relevance, offered follow-up support, shared through established team channels', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-AD-02', 'A', 'Use it in your own practice and mention it if it comes up in conversation.', 'Acquire', 1, false, NULL, NULL, 'No deliberate sharing, passive mention only');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-AD-02', 'B', 'Post the link in the team chat with a brief message saying you found it useful.', 'Acquire', 1, true, 'Posting in a team chat feels like sharing with peers. But a link with a brief endorsement is minimal-effort sharing without context. Deepen requires explaining why it is useful, how to use it, and how it applies to colleagues'' specific contexts.', NULL, 'No contextualised explanation, no application guidance, no curation');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-AD-02', 'C', 'Write a brief guide explaining what the tool does, how you use it in your teaching, and what to watch out for. Share it in your next team meeting with a quick demonstration. Offer to help colleagues set it up.', 'Deepen', 2, false, NULL, 'Contextualised guide, practical demonstration, offered support, shared through structured channel', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-DC-01', 'A', 'Make yourself available as a resource. Tell people they can come to you with questions about AI, share useful tools and tips regularly in team communications, and help individual colleagues when they get stuck.', 'Deepen', 2, true, 'Being a go-to resource and actively supporting colleagues sounds like facilitating professional development. But reactive, unstructured support is sharing (Deepen). Create requires designing and delivering a structured programme.', NULL, 'No programme design, no learning objectives, no structured activities, no evaluation');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-DC-01', 'B', 'Give a presentation to all staff covering the key AI tools and how to use them. Include a Q&A session.', 'Deepen', 2, true, 'A staff-wide presentation feels like professional development delivery. But a single presentation is information delivery, not a development programme. There are no hands-on activities, no progressive skill building, and no follow-up.', NULL, 'No participant practice, no progressive design, no follow-up, no evaluation of learning');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-DC-01', 'C', 'Design a phased programme: start with a needs assessment to understand where staff are. Create a series of hands-on workshops at different levels, with practice tasks between sessions. Provide one-to-one coaching for staff who need extra support. Evaluate the programme through pre and post surveys and observation of changed practice. Iterate based on feedback.', 'Create', 3, false, NULL, 'Needs assessment, phased design, hands-on workshops, coaching, evaluation, iteration', NULL);

INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-DC-02', 'A', 'Share your curated collection of AI resources, tools, and tips with them. Point them to the best training courses available. Check in periodically to see how they are getting on.', 'Deepen', 2, true, 'Curated sharing with follow-up sounds like a mentoring programme. But providing resources and checking in is active sharing (Deepen). Create requires designing structured learning experiences, not just providing curated support.', NULL, 'No designed learning activities, no objectives, no structured progression, no evaluation');
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-DC-02', 'B', 'Design a structured induction programme for new staff that includes: an initial AI readiness assessment, a series of practical workshops building from basic tool use to assessment integration, paired mentoring with experienced AI-using colleagues, and a portfolio task where new teachers document their AI adoption journey. Evaluate the programme after the first cohort and refine it.', 'Create', 3, false, NULL, 'Designed programme with assessment, progressive workshops, mentoring structure, portfolio assessment, evaluation and iteration', NULL);
INSERT INTO scenario_responses (scenario_id, response_key, response_text, maps_to_level_name, maps_to_level_order, is_attractive_nuisance, nuisance_explanation, discriminating_presence, discriminating_absence)
VALUES ('CFT-PL-DC-02', 'C', 'Invite them to observe your lessons where you use AI tools so they can see it in action. Debrief afterwards to answer questions.', 'Deepen', 2, false, NULL, NULL, 'Observation and debrief is informal peer learning, not a designed programme');

-- Counts: 20 scenarios, 62 response options