-- =============================================================================
-- 008: Cross-Framework Mappings
-- Stores validated mappings between framework dimensions/levels
-- =============================================================================

CREATE TABLE cross_framework_mappings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_framework_id TEXT NOT NULL,
  source_dimension_id TEXT NOT NULL,
  source_dimension_name TEXT NOT NULL,
  source_level_id TEXT NOT NULL,
  source_level_name TEXT NOT NULL,
  target_framework_id TEXT NOT NULL,
  target_dimension_id TEXT NOT NULL,
  target_dimension_name TEXT NOT NULL,
  target_level_id TEXT NOT NULL,
  target_level_name TEXT NOT NULL,
  confidence TEXT NOT NULL CHECK (confidence IN ('strong', 'moderate', 'weak', 'non_mapping')),
  direction TEXT NOT NULL CHECK (direction IN ('bidirectional', 'unidirectional_source_implies_target', 'unidirectional_target_implies_source', 'non_mapping')),
  overlap_description TEXT,
  what_transfers TEXT[],
  what_does_not_transfer TEXT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(source_framework_id, source_dimension_id, source_level_id, target_framework_id, target_dimension_id, target_level_id)
);

CREATE INDEX idx_cfm_source ON cross_framework_mappings(source_framework_id, source_dimension_id);
CREATE INDEX idx_cfm_target ON cross_framework_mappings(target_framework_id, target_dimension_id);
CREATE INDEX idx_cfm_confidence ON cross_framework_mappings(confidence);
-- Seed cross-framework mappings (CFT pilot data)
-- Source: reasonlens-research/cft-pilot/cross-framework/mappings.json

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-ethics', 'Ethics of AI', 'tc-et-acquire', 'Acquire', 'digcomp', 'dc-safety-privacy', 'Protecting Personal Data and Privacy (4.2)', 'dc-saf-priv-basic', 'Basic', 'moderate', 'unidirectional_source_implies_target', 'CFT Ethics Acquire requires recognising common ethical issues including privacy and data concerns. DigComp 4.2 Basic requires understanding that digital environments collect personal data and knowing basic privacy protection measures. Both involve awareness of data and privacy concerns. CFT is narrower (AI-specific) while DigComp is broader (all digital technologies).', ARRAY['Awareness that AI tools collect and process personal data', 'Recognition that data privacy is an ethical concern in digital tool use'], ARRAY['CFT''s specific focus on AI bias, transparency, and accountability beyond data privacy', 'DigComp''s coverage of general digital privacy practices (password management, cookie settings, social media privacy) that are not AI-specific']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-ethics', 'Ethics of AI', 'tc-et-deepen', 'Deepen', 'digcomp', 'dc-safety-privacy', 'Protecting Personal Data and Privacy (4.2)', 'dc-saf-priv-inter', 'Intermediate', 'moderate', 'unidirectional_source_implies_target', 'CFT Ethics Deepen requires implementing bias detection checks on AI tools, including investigating data collection and storage practices. DigComp 4.2 Intermediate requires applying privacy settings and managing personal data in digital environments. Both involve active management of data privacy. CFT is more structured and evaluation-focused; DigComp is more about personal data management.', ARRAY['Ability to investigate and evaluate data collection practices of digital tools', 'Active management of privacy settings and data sharing'], ARRAY['CFT''s structured bias detection methodology and documentation requirements', 'DigComp''s broader digital privacy management (GDPR rights, data portability, right to erasure) beyond AI tool evaluation']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-ethics', 'Ethics of AI', 'tc-et-deepen', 'Deepen', 'digcomp', 'dc-comm-citizenship', 'Engaging in Citizenship through Digital Technologies (2.3)', 'dc-cit-inter', 'Intermediate', 'weak', 'unidirectional_source_implies_target', 'CFT Ethics Deepen involves active engagement with ethical AI evaluation. DigComp 2.3 Intermediate involves participating in society through digital technologies and understanding how digital tools affect civic life. The overlap is conceptual: both require active ethical engagement with technology. But CFT focuses on professional tool evaluation while DigComp focuses on civic participation.', ARRAY['Critical awareness of how digital tools affect people and society', 'Active ethical evaluation rather than passive technology consumption'], ARRAY['CFT''s structured tool evaluation methodology', 'DigComp''s focus on civic participation, e-government, and democratic engagement']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-ethics', 'Ethics of AI', 'tc-et-create', 'Create', 'digcomp', 'dc-safety-privacy', 'Protecting Personal Data and Privacy (4.2)', 'dc-saf-priv-adv', 'Advanced', 'moderate', 'unidirectional_source_implies_target', 'CFT Ethics Create requires developing institutional ethical guidelines for AI use. DigComp 4.2 Advanced requires applying complex privacy strategies, guiding others in data protection, and assessing privacy risks of new technologies. Both involve leadership in data protection. CFT is institutional-policy focused; DigComp is broader personal and professional data protection leadership.', ARRAY['Ability to assess data protection implications of new technologies', 'Leadership in guiding others on data protection practices'], ARRAY['CFT''s specific institutional guideline development and governance engagement', 'DigComp''s coverage of advanced personal data protection strategies beyond institutional AI policy']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-foundations', 'AI Foundations', 'tc-fo-acquire', 'Acquire', 'digcomp', 'dc-info-evaluate', 'Evaluating Information (1.2)', 'dc-eval-basic', 'Basic', 'moderate', 'unidirectional_source_implies_target', 'CFT Foundations Acquire requires distinguishing AI from traditional software. DigComp 1.2 Basic requires evaluating the reliability and credibility of digital information sources. A teacher who understands AI vs non-AI can better evaluate whether information came from an AI source. The overlap is indirect: understanding AI systems helps evaluate AI-generated information.', ARRAY['Ability to identify AI-generated content as a distinct category requiring different evaluation', 'Understanding that AI outputs require verification'], ARRAY['CFT''s technical focus on AI system mechanics', 'DigComp''s broader information evaluation skills (source checking, cross-referencing, identifying misinformation) beyond AI-specific content']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-foundations', 'AI Foundations', 'tc-fo-deepen', 'Deepen', 'digcomp', 'dc-info-evaluate', 'Evaluating Information (1.2)', 'dc-eval-inter', 'Intermediate', 'moderate', 'unidirectional_source_implies_target', 'CFT Foundations Deepen requires understanding LLM mechanisms and limitations. DigComp 1.2 Intermediate requires systematically evaluating digital information using defined criteria. Understanding why LLMs hallucinate directly supports systematic evaluation of AI-generated content.', ARRAY['Mechanistic understanding of why AI outputs can be unreliable', 'Ability to apply specific evaluation criteria to AI-generated content'], ARRAY['CFT''s focus on LLM-specific technical understanding', 'DigComp''s broader information evaluation across all digital sources']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-foundations', 'AI Foundations', 'tc-fo-deepen', 'Deepen', 'digcomp', 'dc-content-compthink', 'Computational Thinking and Programming (3.4)', 'dc-comp-inter', 'Intermediate', 'weak', 'unidirectional_target_implies_source', 'CFT Foundations Deepen requires explaining how LLMs work. DigComp 3.4 Intermediate requires understanding and modifying instructions to computing systems. The conceptual overlap is partial: both involve understanding how computational systems process information. But DigComp is broader (programming, algorithms, abstraction) while CFT is specifically about LLMs.', ARRAY['General understanding that computational systems follow defined processes', 'Conceptual framework for understanding AI as a type of computational system'], ARRAY['CFT''s specific LLM mechanics (training, prediction, hallucination)', 'DigComp''s programming, algorithm design, and general computational thinking skills']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-foundations', 'AI Foundations', 'tc-fo-create', 'Create', 'digcomp', 'dc-content-develop', 'Developing Digital Content (3.1)', 'dc-dev-adv', 'Advanced', 'weak', 'unidirectional_source_implies_target', 'CFT Foundations Create requires designing learning activities about AI principles. DigComp 3.1 Advanced requires creating complex digital content autonomously. Creating educational content about AI is a form of digital content creation. The overlap is conceptual but the competencies focus on very different things.', ARRAY['Ability to create digital educational content about technology concepts', 'Autonomous complex content creation capability'], ARRAY['CFT''s pedagogical design focus (learning objectives, assessment, iteration)', 'DigComp''s broader content creation skills (multimedia, interactive content, coding)']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-human-centered', 'Human-Centered Mindset', 'tc-hc-acquire', 'Acquire', 'digcomp', 'dc-safety-wellbeing', 'Supporting Wellbeing (4.3)', 'dc-well-basic', 'Basic', 'moderate', 'unidirectional_source_implies_target', 'CFT Human-Centered Acquire requires recognising AI''s supportive (not replacing) role. DigComp 4.3 Basic requires awareness of how digital technologies affect personal wellbeing. Both involve awareness of technology''s impact on people. CFT frames this as AI agency preservation; DigComp frames it as broader digital wellbeing.', ARRAY['Awareness that technology should serve human needs, not dominate them', 'Recognition of both benefits and risks of technology in human contexts'], ARRAY['CFT''s specific focus on AI replacing human professional judgement', 'DigComp''s broader wellbeing concerns (screen time, digital addiction, ergonomics, cyberbullying)']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-human-centered', 'Human-Centered Mindset', 'tc-hc-create', 'Create', 'digcomp', 'dc-problem-creative', 'Identifying Creative Solutions Using Digital Technologies (5.3)', 'dc-creat-adv', 'Advanced', 'weak', 'unidirectional_source_implies_target', 'CFT Human-Centered Create requires leading institutional conversations on human-centered AI. DigComp 5.3 Advanced requires applying a human-centric approach to innovation. Both reference human-centricity in technology decisions. But CFT is about institutional AI governance while DigComp is about innovation problem-solving.', ARRAY['Human-centric approach to technology decision-making', 'Ability to lead others in considering human needs in technology adoption'], ARRAY['CFT''s institutional governance focus', 'DigComp''s broader creative problem-solving and innovation beyond human-centered AI governance']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-professional', 'Professional Learning', 'tc-pl-acquire', 'Acquire', 'digcomp', 'dc-problem-digcomp', 'Identifying and Addressing Digital Competence Needs (5.4)', 'dc-digcomp-basic', 'Basic', 'strong', 'unidirectional_source_implies_target', 'CFT Professional Learning Acquire requires attending AI training sessions. DigComp 5.4 Basic requires recognising gaps in digital competence and seeking learning opportunities. Both involve identifying learning needs and engaging in structured professional development. This is the strongest single-mapping in the CFT-DigComp pair.', ARRAY['Recognition of personal digital competence gaps', 'Active engagement in structured professional learning'], ARRAY['CFT''s AI-specific focus', 'DigComp''s coverage of all digital competence areas beyond AI']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-professional', 'Professional Learning', 'tc-pl-deepen', 'Deepen', 'digcomp', 'dc-problem-digcomp', 'Identifying and Addressing Digital Competence Needs (5.4)', 'dc-digcomp-inter', 'Intermediate', 'strong', 'unidirectional_source_implies_target', 'CFT Professional Learning Deepen requires actively sharing AI resources with peers. DigComp 5.4 Intermediate requires helping others develop their digital competence. Both involve contributing to others'' learning. This is a strong, bidirectional mapping.', ARRAY['Active contribution to peers'' digital competence development', 'Curated, contextualised resource sharing'], ARRAY['CFT''s AI-specific sharing focus', 'DigComp''s broader digital competence development support']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-professional', 'Professional Learning', 'tc-pl-create', 'Create', 'digcomp', 'dc-problem-digcomp', 'Identifying and Addressing Digital Competence Needs (5.4)', 'dc-digcomp-adv', 'Advanced', 'strong', 'unidirectional_source_implies_target', 'CFT Professional Learning Create requires facilitating AI professional development programmes. DigComp 5.4 Advanced requires guiding others in developing their digital competence through structured approaches. Both involve professional development leadership. This is the cleanest mapping in the pair.', ARRAY['Ability to design and facilitate structured digital competence development', 'Evaluation of professional development impact'], ARRAY['CFT''s AI-specific programme content', 'DigComp''s broader digital competence development across all areas']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-pedagogy', 'AI Pedagogy', 'undefined', 'undefined', 'digcomp', 'undefined', '', 'undefined', 'undefined', 'non_mapping', 'non_mapping', 'DigComp 3.0 is a citizen-facing framework, not an educator-specific one. It has no competence area addressing teaching practice, curriculum design, or formative assessment integration. AI Pedagogy has no genuine equivalent in DigComp. The closest competence (5.3 Creative Solutions) addresses human-centric innovation but not pedagogical design. DigiCompEdu would be the appropriate DigComp-family framework for mapping AI Pedagogy.', NULL, ARRAY['CFT AI Pedagogy''s entire scope: lesson preparation with AI, formative assessment integration, curriculum design', 'No DigComp competence addresses teaching, learning design, or assessment']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-human-centered', 'Human-Centered Mindset', 'tc-hc-acquire', 'Acquire', 'bdc-teacher-he', 'bdc-identity-wellbeing', 'Digital Identity and Wellbeing (Element 6)', 'bdc-idwell-developing', 'Developing', 'moderate', 'unidirectional_source_implies_target', 'CFT Human-Centered Acquire requires recognising AI''s supportive role. BDC Element 6 at Developing level involves awareness of digital wellbeing and the impact of technology on professional identity. Both involve awareness of technology''s impact on the teaching profession. CFT is AI-specific and frames this as agency preservation; BDC is broader and covers digital identity, stress, and work-life balance.', ARRAY['Awareness that digital technologies affect professional identity and agency', 'Recognition of the need to maintain professional judgement in technology-mediated work'], ARRAY['CFT''s specific AI-replacement framing', 'BDC''s broader digital identity management, digital wellbeing, and work-life balance concerns']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-human-centered', 'Human-Centered Mindset', 'tc-hc-deepen', 'Deepen', 'bdc-teacher-he', 'bdc-identity-wellbeing', 'Digital Identity and Wellbeing (Element 6)', 'bdc-idwell-capable', 'Capable', 'moderate', 'unidirectional_source_implies_target', 'CFT Human-Centered Deepen requires applying inclusive design principles when selecting AI tools. BDC Element 6 at Capable level involves ensuring equality of access to digital opportunity and supporting learners'' digital identities. Both involve active attention to equity and inclusion in digital tool use. CFT focuses on tool selection evaluation; BDC frames this as supporting learner digital equity.', ARRAY['Active evaluation of digital tools for equity and inclusion', 'Concern for differential impact of technology on different groups'], ARRAY['CFT''s structured evaluation methodology for AI tool selection', 'BDC''s broader digital identity management and learner digital identity support']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-ethics', 'Ethics of AI', 'tc-et-acquire', 'Acquire', 'bdc-teacher-he', 'bdc-info-data-media', 'Information, Data and Media Literacies (Element 2)', 'bdc-idm-developing', 'Developing', 'moderate', 'unidirectional_source_implies_target', 'CFT Ethics Acquire requires recognising common ethical issues in AI. BDC Element 2 at Developing level includes awareness of data ethics and security in the data literacy sub-element. Both involve ethical awareness around data and digital tools. CFT is AI-specific; BDC covers broader data and information literacy.', ARRAY['Awareness of data ethics concerns in digital tool use', 'Recognition that data collection and use raise ethical questions'], ARRAY['CFT''s AI-specific ethical issues (algorithmic bias, transparency, accountability)', 'BDC''s broader data literacy (managing datasets, running queries, interpreting data) and media literacy']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-ethics', 'Ethics of AI', 'tc-et-deepen', 'Deepen', 'bdc-teacher-he', 'bdc-info-data-media', 'Information, Data and Media Literacies (Element 2)', 'bdc-idm-capable', 'Capable', 'moderate', 'unidirectional_source_implies_target', 'CFT Ethics Deepen requires implementing bias detection checks on AI tools. BDC Element 2 at Capable level involves evaluating digital information critically and applying data ethics in practice. Both require active ethical evaluation of digital tools and data practices. CFT focuses on structured AI bias detection; BDC covers broader critical information and data evaluation.', ARRAY['Structured evaluation of digital tool data practices', 'Applied data ethics in professional practice'], ARRAY['CFT''s specific bias detection methodology', 'BDC''s broader information and media literacy skills']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-foundations', 'AI Foundations', 'tc-fo-acquire', 'Acquire', 'bdc-teacher-he', 'bdc-proficiency-productivity', 'Digital Proficiency and Productivity (Element 1)', 'bdc-pp-developing', 'Developing', 'moderate', 'unidirectional_source_implies_target', 'CFT Foundations Acquire requires explaining what AI is vs traditional software. BDC Element 1 at Developing level involves functional understanding of ICT systems and digital tools. Both require foundational understanding of how digital systems work. CFT is specifically about the AI/non-AI distinction; BDC covers broader digital proficiency.', ARRAY['Functional understanding of digital tool categories and how they operate', 'Ability to distinguish between different types of digital systems'], ARRAY['CFT''s specific AI vs traditional software distinction', 'BDC''s broader ICT proficiency (hardware, software, input methods, file management)']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-foundations', 'AI Foundations', 'tc-fo-deepen', 'Deepen', 'bdc-teacher-he', 'bdc-proficiency-productivity', 'Digital Proficiency and Productivity (Element 1)', 'bdc-pp-capable', 'Capable', 'weak', 'unidirectional_source_implies_target', 'CFT Foundations Deepen requires understanding LLM mechanisms and limitations. BDC Element 1 at Capable level involves confident and critical use of ICT applications with awareness of benefits and constraints. The conceptual overlap is in critical understanding of digital tool capabilities and limitations, but CFT is specifically about LLM architecture while BDC is about general digital tool proficiency.', ARRAY['Critical understanding of digital tool capabilities and limitations', 'Informed decision-making about when to use and when not to use specific tools'], ARRAY['CFT''s LLM-specific technical knowledge (prediction mechanisms, hallucination, training data)', 'BDC''s broader ICT proficiency across all digital tools and systems']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-pedagogy', 'AI Pedagogy', 'tc-pd-acquire', 'Acquire', 'bdc-teacher-he', 'bdc-learning-development', 'Digital Learning and Development (Element 5)', 'bdc-ld-developing', 'Developing', 'strong', 'unidirectional_source_implies_target', 'CFT Pedagogy Acquire requires using AI for basic lesson preparation. BDC Element 5 at Developing level involves using digital tools for planning and designing learning opportunities. Both require using digital tools for teaching preparation. This is the strongest mapping in the CFT-BDC pair because BDC Element 5 is the core pedagogical element explicitly adapted for HE teaching contexts.', ARRAY['Use of digital tools for lesson and resource preparation', 'Integration of technology into teaching planning workflows'], ARRAY['CFT''s AI-specific tool focus (LLMs, AI generators)', 'BDC''s broader digital teaching tools (VLEs, lecture capture, polling tools, digital whiteboards)']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-pedagogy', 'AI Pedagogy', 'tc-pd-deepen', 'Deepen', 'bdc-teacher-he', 'bdc-learning-development', 'Digital Learning and Development (Element 5)', 'bdc-ld-capable', 'Capable', 'strong', 'unidirectional_source_implies_target', 'CFT Pedagogy Deepen requires integrating AI into formative assessment. BDC Element 5 at Capable level involves using digital tools for assessment (quizzes, self-assessment, peer assessment) and adapting teaching in response to digitally collected feedback. Both require active technology integration into the assessment and feedback cycle. BDC provides the broader digital assessment context into which AI integration fits.', ARRAY['Integration of digital tools into formative assessment', 'Using technology-generated data to adapt teaching', 'Designed use of technology in the feedback loop'], ARRAY['CFT''s AI-specific assessment integration (LLM feedback, AI-powered adaptive learning)', 'BDC''s non-AI digital assessment tools (VLE quizzes, polling, e-portfolios, digital rubrics)']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-pedagogy', 'AI Pedagogy', 'tc-pd-create', 'Create', 'bdc-teacher-he', 'bdc-learning-development', 'Digital Learning and Development (Element 5)', 'bdc-ld-proficient', 'Proficient', 'strong', 'unidirectional_source_implies_target', 'CFT Pedagogy Create requires creating innovative AI-enhanced curricula. BDC Element 5 at Proficient level involves leading curriculum innovation with digital technologies, collaboratively planning and reviewing courses digitally, and contributing to scholarship of teaching with technology. Both involve curriculum-level digital innovation and leadership in pedagogical technology integration.', ARRAY['Curriculum-level innovation with digital technologies', 'Collaborative development and evaluation of technology-enhanced curricula', 'Sharing of pedagogical innovation with the broader community'], ARRAY['CFT''s AI-specific curriculum innovation focus', 'BDC''s broader digital teaching innovation (online learning design, blended learning, open educational resources)']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-professional', 'Professional Learning', 'tc-pl-acquire', 'Acquire', 'bdc-teacher-he', 'bdc-learning-development', 'Digital Learning and Development (Element 5)', 'bdc-ld-developing', 'Developing', 'strong', 'unidirectional_source_implies_target', 'CFT Professional Learning Acquire requires attending AI training sessions. BDC Element 5 at Developing level includes undertaking CPD as a teacher using digital tools. Both involve engaging in structured professional development about technology in education.', ARRAY['Engagement in technology-focused professional development', 'Self-directed learning about digital tools for teaching'], ARRAY['CFT''s AI-specific training focus', 'BDC''s broader digital CPD including online facilitation, VLE use, and digital pedagogy']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-professional', 'Professional Learning', 'tc-pl-deepen', 'Deepen', 'bdc-teacher-he', 'bdc-communication-collaboration', 'Digital Communication, Collaboration and Participation (Element 4)', 'bdc-ccp-capable', 'Capable', 'moderate', 'unidirectional_source_implies_target', 'CFT Professional Learning Deepen requires actively sharing AI resources with peers. BDC Element 4 at Capable level involves contributing to digital networks and sharing resources through digital channels. Both involve active, contextualised sharing of professional knowledge through digital means.', ARRAY['Active participation in professional digital networks', 'Contextualised resource sharing through digital channels'], ARRAY['CFT''s AI-specific content focus', 'BDC''s broader digital communication skills (online teaching communication, digital collaboration, webinar facilitation)']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-professional', 'Professional Learning', 'tc-pl-create', 'Create', 'bdc-teacher-he', 'bdc-learning-development', 'Digital Learning and Development (Element 5)', 'bdc-ld-proficient', 'Proficient', 'strong', 'unidirectional_source_implies_target', 'CFT Professional Learning Create requires facilitating AI professional development programmes. BDC Element 5 at Proficient level involves leading organisational change projects in response to digital developments and facilitating colleagues'' digital capability development. Both involve professional development leadership and programme facilitation.', ARRAY['Design and facilitation of technology-focused professional development', 'Leadership of colleagues'' digital capability development', 'Evaluation of professional development impact'], ARRAY['CFT''s AI-specific programme content', 'BDC''s broader digital change leadership (VLE migration, online learning transformation, digital assessment introduction)']);

INSERT INTO cross_framework_mappings (source_framework_id, source_dimension_id, source_dimension_name, source_level_id, source_level_name, target_framework_id, target_dimension_id, target_dimension_name, target_level_id, target_level_name, confidence, direction, overlap_description, what_transfers, what_does_not_transfer)
VALUES ('teacher-competency', 'tc-foundations', 'AI Foundations', 'tc-fo-create', 'Create', 'bdc-teacher-he', 'bdc-creation-innovation', 'Digital Creation, Problem-Solving and Innovation (Element 3)', 'bdc-cpi-proficient', 'Proficient', 'moderate', 'unidirectional_source_implies_target', 'CFT Foundations Create requires designing learning activities about AI principles. BDC Element 3 at Proficient level involves designing interactive learning resources and leading innovation projects. Both involve creating digital educational resources and innovating in educational practice.', ARRAY['Design of original digital learning resources', 'Innovation leadership in educational technology'], ARRAY['CFT''s focus on AI-principles-as-content (teaching about AI itself)', 'BDC''s broader digital creation skills (coding, app development, virtual environments, multimedia production)']);

-- Total: 27 mappings